name: Playwright Automated QA

on:
  workflow_dispatch:
    inputs:
      target_urls:
        description: '검증할 타겟 웹페이지 URL 목록 (JSON 배열 형태)'
        required: true
        type: string

jobs:
  test:
    timeout-minutes: 15 # 다중 검사일 경우를 대비해 15분으로 넉넉하게 늘립니다.
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: lts/*
        
    - name: Install dependencies
      run: npm ci
      
    - name: Install Playwright Browsers
      run: npx playwright install --with-deps
      
    - name: Run Playwright tests
      env:
        # 변경된 입력값을 환경 변수로 넘깁니다.
        TARGET_URLS: ${{ inputs.target_urls }} 
      run: npx playwright test